#
# Makefile for the Novatek NT383x0 touchscreen driver.
#

# Each configuration option enables a list of files.

touch_nt383x0-y := nt383x0.o nt383x0_fw_update.o nt383x0_ext_proc.o nt383x0_mp_ctrlram.o

obj-$(CONFIG_TOUCHSCREEN_NT383x0) += touch_nt383x0.o
